// APP
export const SET_APP_VERSION = "SET_APP_VERSION";
export const RESET_APP_PURGE = "RESET_APP_PURGE";

// AJAX
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_COMPLETE = "FETCH_COMPLETE";
export const REQUEST_ABORT_ALL = "REQUEST_ABORT_ALL";
export const REQUEST_ADD = "REQUEST_ADD";
export const REQUEST_REMOVE = "REQUEST_REMOVE";

// ROUTE
export const ROUTE_CHANGE = "ROUTE_CHANGE";
export const ROUTE_CHANGE_END = "ROUTE_CHANGE_END";
export const ROUTE_BEFORE_UNLOAD = "ROUTE_BEFORE_UNLOAD";
export const ROUTE_UPDATE_TITLE = "ROUTE_UPDATE_TITLE";

// TOAST
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

// AUTH
export const USER_LOGGEDIN = "USER_LOGGEDIN";
export const USER_LOGGEDOUT = "USER_LOGGEDOUT";

